version: "3.1"
networks:
  proxynet:
    driver: bridge

services:

  bd:
    build:
      context: .
      dockerfile: compose/Dockerfile
    networks:
      - proxynet
    ports:
      - "27:27017"

  backend:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "8088:8088"
    networks:
      - proxynet
    depends_on:
      - bd


