version: "3.1"
networks:
  proxynet:
    driver: bridge

services:

  bd:
    build:
      context: .
      dockerfile: compose/Dockerfile
    networks:
      - proxynet

  backend:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "8088:8088"
    networks:
      - proxynet


